# Jekyll Config

#title: AOGDP Map Viewers
#locale: en_US
#description: Describe your website here.
#logo: site-logo.png
#url: maps.aogdp.org or viewers.aogdp.org

# Jekyll configuration

#permalink:   /:title/
#markdown:    kramdown
#highlighter: rouge
#sass:
#  sass_dir: _sass
#  style: compressed

# Hexo Config npm install hexo

# Hexo Configuration
## Docs: http://zespia.tw/hexo/docs/configuration.html
## Source: https://github.com/tommy351/hexo/

# Site
title: AOGDP Map Viewers
#subtitle:
#description:
#author: John Doe
#email:
#language:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://viewers.aogdp.org
root: /
permalink: :title/
#tag_dir: tags
#archive_dir: archives
#category_dir: categories
#code_dir: downloads/code
